---

common:
  follow: false
  setting1: 'Value 1'
  setting3:
    key: value

  setting6:
    ops: vops
    key: value
    key2:
      tt: new
      dd: new

  setting4: 'blah blah'
  setting5:
    key5: value5

group3:
  fee: '100500'

group1:
  baz: bars
  foo: bar
  nest: str
